// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxlztuciqafqfmlovved.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bHp0dWNpcWFmcWZtbG92dmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzk3NjgsImV4cCI6MjA2ODg1NTc2OH0.T3y1YurrOZwrHDBkPL2TzDaRrx7Mn0wPnccMGOf20HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});